package com.codebyallan.todo_list.entity

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import org.hibernate.annotations.CreationTimestamp
import org.hibernate.annotations.UpdateTimestamp
import java.time.Instant

/**
 * Represents the [Task] entity that will be mapped to a table in the database.
 *  This class contains all the data for a single task.
 */
@Entity
data class Task(
    /**
     * The unique identifier of the table is of type long.
     * Is automatically generated by the database.
     */
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) val id: Long? = null,
    /**
     * Title is of type String and required.
     */
    var title: String = "",
    /**
     * Description is of type String and optional.
     */
    var description: String? = "",
    /**
     * IsDone is of type  Boolean.
     * Default value is false.
     */
    @Column(name = "is_done") var isDone: Boolean = false,
    /**
     * The timestamp indicating when the task was first created.
     * Automatically set by Hibernate on initial persistence.
     */
    @CreationTimestamp @Column(name = "created_at") val createdAt: Instant? = null,
    /**
     * The timestamp indicating the last time the task was modified.
     * Automatically updated by Hibernate on every change.
     */
    @UpdateTimestamp @Column(name = "updated_at") val updatedAt: Instant? = null
)